### ISSUE TITLE
Adopt PSR 1 and 2

### ISSUE THREAD

**Issue by ghost** [idslot/idslot#2]
https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-1-basic-coding-standard.md

https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md

**Comment by 390** [comment]
Thanks Drak, but Codeigniter use different [coding style](http://idslot.org/devguide/general/styleguide.html).
But I've problem with this issue, and Idslot need fixes about this.
